### ISSUE TITLE
Filters do not work

### ISSUE THREAD

**Issue by dgarijo** [SoftwareUnderstanding/SOMEF-Vider#24]
I tried to test the filters by clicking on the right part of the logo here:
![Screenshot from 2021-12-15 11-36-11](https://user-images.githubusercontent.com/1520666/146171166-ef90d943-7862-466f-9578-c1cb7cf7531d.png)
but the requests to the server don't change and the content does not change, even after clicking "apply"

**Comment by Vitoriox** [comment]
#14
Will be corrected when issue 14 is finished

**Comment by dgarijo** [comment]
Got it, I understand this is work in progress. I will close the issue then.
Superseeded by #14.
