### ISSUE TITLE
What does this do?

### ISSUE THREAD

**Issue by dgarijo** [SoftwareUnderstanding/SOMEF-Vider#25]
I have no idea about what the middle button here does:
![Screenshot from 2021-12-15 11-36-11](https://user-images.githubusercontent.com/1520666/146171375-63791086-e7d0-4d5d-a983-80ef3648fe64.png)
I don't see any impact in the application

**Comment by Vitoriox** [comment]
#12 
Is the button for the software card, not finished yet

**Comment by dgarijo** [comment]
Excellent
