### ISSUE TITLE
Footer with UPM and OEG logos

### ISSUE THREAD

**Issue by dgarijo** [SoftwareUnderstanding/SOMEF-Vider#31]
Please take the logos from here:
https://foops.linkeddata.es/FAIR_validator.html
You don't need to add the contact/creators, but we should have all logos.

**Comment by dgarijo** [comment]
This is high priority

**Comment by dgarijo** [comment]
Some changes:

- 2021 - SOMEF Vider should be on the right.
- Make logos hyperlinks
- Add pointer to github repo
- make logos a little bit smaller (not too much)

**Comment by Vitoriox** [comment]
Fix overlaping with main view
