### ISSUE TITLE
Improve how citations appear

### ISSUE THREAD

**Issue by dgarijo** [SoftwareUnderstanding/SOMEF-Vider#37]
For example, we see:
```
Garijo, D. (2017). WIDOCO: a wizard for documenting ontologies. International Semantic Web Conference, 94–102. https://doi.org/10.1007/978-3-319-68204-4_9

@inproceedings{garijo2017widoco, title={WIDOCO: a wizard for documenting ontologies}, author={Garijo, Daniel}, booktitle={International Semantic Web Conference}, pages={94--102}, year={2017}, organization={Springer, Cham}, doi = {10.1007/978-3-319-68204-4_9}, funding = {USNSF ICER-1541029, NIH 1R01GM117097-01}, url={http://dgarijo.com/papers/widoco-iswc2017.pdf} }
```
Instead, I would like to see the bibtex properly formatted as a text block. The citation would be great as something that could be copied/pasted in the model card.

**Comment by Vitoriox** [comment]
SOMEF-Vider process citation in 2 ways, depending on the content format:

 - 1) If the BibTeX comes with markdown notation, the application shows it like this:
![image](https://user-images.githubusercontent.com/59898208/146937266-44f38535-89ea-45be-80a5-f16625c0f5d9.png)

 - 2) if the BibTeX retrieved from SOMEF arrives as plain text, the application converts it to APA citation style, as you saw in your comment.

What I understand from your comment is that you would like to see the BibTeX formatted as if it always comes with Markdown, (Option 1) even if it doesn't. Is that so?

**Comment by dgarijo** [comment]
I think that showing both as in my comment is confusing. We should have the means to copy the APA style, or distinguish that the APA style is generated from the bibtex somehow. 
This issue is low priority
