### ISSUE TITLE
When returning from "About" the app refreshes the page

### ISSUE THREAD

**Issue by dgarijo** [SoftwareUnderstanding/SOMEF-Vider#43]
If I have a result and go to the "About" page, when I come back the results are reset. I would like the results to be preserved

**Comment by Vitoriox** [comment]
That is because history mode of Vue Router is disabled. 
Enabling this can cause the application to go "slower" in some cases (For example, swapping between pages will be slower)

The history mode can be enabled if you request so.

**Comment by dgarijo** [comment]
How much slower? If this delay is like .5 sec, then it's fine. It it's 2 seconds, then it's not fine

**Comment by Vitoriox** [comment]
Solved in the code cleanup
