### ISSUE TITLE
Demo is DOWN

### ISSUE THREAD

**Issue by EvaMart** [SoftwareUnderstanding/SOMEF-Vider#58]
Hello, 

I am trying to access [https://somef.linkeddata.es/](https://somef.linkeddata.es/) and I can't. It seems down.

**Comment by dgarijo** [comment]
Thanks for reaching out. 
Unfortunately, the servers at UPM are under maintenance, expected to come back tomorrow.
In the meantime, I recommend having a look at the somef docker image in https://github.com/KnowledgeCaptureAndDiscovery/somef/.  The somef vider demo is using an older version of somef.

**Comment by dgarijo** [comment]
Demo is up, but the version of somef that runs is a bit dated and does not show all the metadata it should.
We will be releasing in the next months a newer version

**Comment by dgarijo** [comment]
Demo now runs the latest somef version.
